# Generated by Django 4.2.7 on 2026-06-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('en_espera', 'En espera de consulta'), ('cancelada', 'Cancelada'), ('atendida', 'Atendida')], default='pendiente', max_length=20),
        ),
    ]
