# Generated by Django 4.2.7 on 2026-07-07 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0002_fase1_cierre'),
        ('pacientes', '0002_contacto_extendido'),
        ('consulta', '0001_initial'),
        ('core', '0006_qr_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordatorioMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(max_length=200)),
                ('dosis', models.CharField(blank=True, max_length=100)),
                ('frecuencia', models.CharField(choices=[('diario', 'Diario'), ('12h', 'Cada 12 horas'), ('8h', 'Cada 8 horas')], default='diario', max_length=20)),
                ('hora_recordatorio', models.TimeField()),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consulta.consulta')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.institucion')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios_medicamentos', to='pacientes.paciente')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='LogNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cita_24h', 'Recordatorio cita 24h'), ('cita_1h', 'Recordatorio cita 1h'), ('medicamento', 'Recordatorio medicamento')], max_length=20)),
                ('destinatario', models.EmailField(blank=True, max_length=254)),
                ('asunto', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('enviado', 'Enviado'), ('fallido', 'Fallido'), ('omitido', 'Omitido')], max_length=20)),
                ('detalle', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs_notificacion', to='citas.cita')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.institucion')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
                ('recordatorio_medicamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notificaciones.recordatoriomedicamento')),
            ],
            options={
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['institucion', 'tipo', 'creado_en'], name='notificacio_institu_a98b3d_idx'), models.Index(fields=['recordatorio_medicamento', 'creado_en'], name='notificacio_recorda_61fda1_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='lognotificacion',
            constraint=models.UniqueConstraint(condition=models.Q(('cita__isnull', False), ('estado', 'enviado')), fields=('cita', 'tipo'), name='uniq_log_cita_tipo_enviado'),
        ),
    ]
