# Generated by Django 4.2.7 on 2026-06-11 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_backuplog'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREATE', 'CREATE'), ('UPDATE', 'UPDATE'), ('DELETE', 'DELETE')], max_length=20)),
                ('tabla_afectada', models.CharField(max_length=50)),
                ('registro_id', models.IntegerField(blank=True, null=True)),
                ('valor_anterior', models.JSONField(blank=True, null=True)),
                ('valor_nuevo', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.institucion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['institucion', 'creado_en'], name='core_logaud_institu_fd626e_idx'), models.Index(fields=['tabla_afectada'], name='core_logaud_tabla_a_a54b31_idx')],
            },
        ),
    ]
