# Generated by Django 4.2.7 on 2026-06-11 14:37

import apps.qr.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0002_contacto_extendido'),
        ('consulta', '0001_initial'),
        ('core', '0005_referencias_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('citas', '0002_fase1_cierre'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=apps.qr.models.generar_token_qr, max_length=64, unique=True)),
                ('tipo', models.CharField(choices=[('receta', 'Receta'), ('examen', 'Orden de examen'), ('checkin', 'Check-in de cita')], max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('usado', models.BooleanField(default=False)),
                ('usado_en', models.DateTimeField(blank=True, null=True)),
                ('expira_en', models.DateTimeField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='citas.cita')),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consulta.consulta')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.institucion')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
            options={
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['institucion', 'tipo'], name='qr_document_institu_1525e2_idx'), models.Index(fields=['token'], name='qr_document_token_95393e_idx')],
            },
        ),
    ]
