# Generated by Django 4.2.7 on 2026-07-07 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_qr_rls'),
        ('consulta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariableClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('texto', 'Texto'), ('numero', 'Numero'), ('booleano', 'Booleano'), ('fecha', 'Fecha'), ('select', 'Seleccion')], max_length=20)),
                ('opciones', models.JSONField(blank=True, default=list)),
                ('obligatorio', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables_clinicas', to='core.especialidad')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.institucion')),
            ],
            options={
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ValorVariableClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.TextField(blank=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_variables', to='consulta.consulta')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.institucion')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='valores', to='variables_clinicas.variableclinica')),
            ],
        ),
        migrations.AddIndex(
            model_name='variableclinica',
            index=models.Index(fields=['institucion', 'especialidad', 'activo'], name='variables_c_institu_68f522_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='variableclinica',
            unique_together={('institucion', 'especialidad', 'codigo')},
        ),
        migrations.AddIndex(
            model_name='valorvariableclinica',
            index=models.Index(fields=['institucion', 'consulta'], name='variables_c_institu_28a7c3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='valorvariableclinica',
            unique_together={('consulta', 'variable')},
        ),
    ]
