# Generated by Django 4.2.30 on 2026-07-17 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='theme',
            field=models.CharField(choices=[('vital', 'Vital'), ('garden', 'Garden'), ('emerald', 'Esmeralda'), ('aqua', 'Aqua'), ('corporate', 'Corporativo'), ('light', 'Claro'), ('dark', 'Oscuro'), ('cupcake', 'Suave'), ('bumblebee', 'Amarillo'), ('winter', 'Invierno'), ('night', 'Noche'), ('forest', 'Bosque'), ('lofi', 'Minimalista')], default='vital', max_length=30),
        ),
    ]
