# Generated by Django 4.2.7 on 2026-07-07 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consulta', '0001_initial'),
        ('core', '0009_pacientes_ocr_rls'),
        ('preclinica', '0001_initial'),
        ('citas', '0002_fase1_cierre'),
        ('pacientes', '0003_documentoocrlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrediccionAusentismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probabilidad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nivel', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], max_length=10)),
                ('factores', models.JSONField(blank=True, default=dict)),
                ('calculado_en', models.DateTimeField(auto_now=True)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prediccion_ausentismo', to='citas.cita')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.institucion')),
            ],
            options={
                'ordering': ['-calculado_en'],
                'indexes': [models.Index(fields=['institucion', 'nivel'], name='ia_predicti_institu_e4492a_idx')],
            },
        ),
        migrations.CreateModel(
            name='DemandaCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField()),
                ('franja_horaria', models.CharField(max_length=20)),
                ('demanda_esperada', models.DecimalField(decimal_places=2, max_digits=6)),
                ('muestras', models.PositiveIntegerField(default=0)),
                ('calculado_en', models.DateTimeField(auto_now=True)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.especialidad')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.institucion')),
            ],
            options={
                'ordering': ['-demanda_esperada'],
                'unique_together': {('institucion', 'especialidad', 'dia_semana', 'franja_horaria')},
            },
        ),
        migrations.CreateModel(
            name='AlertaRiesgoCronico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('diabetes', 'Diabetes'), ('hta', 'Hipertension'), ('otro', 'Otro')], max_length=20)),
                ('nivel', models.CharField(choices=[('bajo', 'Bajo'), ('medio', 'Medio'), ('alto', 'Alto')], max_length=10)),
                ('mensaje', models.TextField()),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='citas.cita')),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='consulta.consulta')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.institucion')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_riesgo', to='pacientes.paciente')),
                ('preclinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='preclinica.preclinica')),
            ],
            options={
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['institucion', 'paciente', 'activa'], name='ia_predicti_institu_e0a3bf_idx'), models.Index(fields=['tipo', 'nivel'], name='ia_predicti_tipo_4dc287_idx')],
            },
        ),
    ]
