# Generated by Django 4.2.7 on 2026-07-07 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pacientes', '0003_documentoocrlog'),
        ('core', '0009_pacientes_ocr_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.institucion')),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_portal', to='pacientes.paciente')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_paciente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil de paciente',
                'verbose_name_plural': 'perfiles de paciente',
            },
        ),
    ]
