# Generated by Django 4.2.7 on 2026-06-11 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0002_fase1_cierre'),
        ('consulta', '0001_initial'),
        ('core', '0004_enable_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('completada', 'Completada')], default='pendiente', max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='media', max_length=20)),
                ('motivo', models.TextField()),
                ('comentarios_especialista', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cita_derivada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referencias', to='citas.cita')),
                ('consulta_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referencias', to='consulta.consulta')),
                ('especialidad_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referencias_recibidas', to='core.especialidad')),
                ('especialista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referencias_asignadas', to='core.profesional')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.institucion')),
                ('medico_referente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referencias_emitidas', to='core.profesional')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Contrarreferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumen_atencion', models.TextField()),
                ('plan_seguimiento', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.profesional')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.institucion')),
                ('referencia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrarreferencia', to='referencias.referencia')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddIndex(
            model_name='referencia',
            index=models.Index(fields=['institucion', 'estado'], name='referencias_institu_578d86_idx'),
        ),
        migrations.AddIndex(
            model_name='referencia',
            index=models.Index(fields=['consulta_origen'], name='referencias_consult_e16515_idx'),
        ),
    ]
